version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
